"""add kode_suratKeluar dan jenis_suratKeluar ke SuratKeluar

Revision ID: 77b7ce504c73
Revises: 
Create Date: 2025-07-24 04:15:58.407262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b7ce504c73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surat_keluar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kode_suratKeluar', sa.String(length=100), nullable=False, server_default='Not found'))
        batch_op.add_column(sa.Column('jenis_suratKeluar', sa.String(length=100), nullable=False, server_default='Not found'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surat_keluar', schema=None) as batch_op:
        batch_op.drop_column('jenis_suratKeluar')
        batch_op.drop_column('kode_suratKeluar')

    # ### end Alembic commands ###
